# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_design.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_design.ipynb 3
from .motor import evaluate
from .utilities import *
from .battery import Cell, Battery
import numpy as np
from fastcore.utils import *
