# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_utilities.ipynb.

# %% auto 0
__all__ = ['Nm_to_Ftlbs', 'Ft_lbs_to_Nm', 'Inch_lbs_to_Nm', 'Kg_to_lbs', 'lbs_to_Kg', 'meters_to_miles', 'feet_to_meters',
           'meters_to_inches']

# %% ../nbs/02_utilities.ipynb 3
#| export

# %% ../nbs/02_utilities.ipynb 5
def Nm_to_Ftlbs(Nm): 
    """ Convert Nm to ft-lbs """
    return Nm * 0.737562149
    
def Ft_lbs_to_Nm(ft_lbs):
    """ Convert ft-lbs to Nm """
    return ft_lbs * 1.35581795

def Inch_lbs_to_Nm(inch_lbs):
    """ Convert inch-lbs to Nm """
    return inch_lbs * 0.112984829

def Kg_to_lbs(kg):
    """ Convert kg to lbs """
    return round(kg * 2.20462262)

def lbs_to_Kg(lbs):
    """ Convert lbs to kg """
    return lbs * 0.45359237

def meters_to_miles(meters):
    """ Convert meters to miles """
    return meters * 0.000621371

def feet_to_meters(feet):
    """ Convert feet to meters """
    return feet * 0.3048

def meters_to_inches(meters):
    """ Convert meters to inches """
    return meters * 39.3700787
